name: CI/CD TutorialBox

on:
  push:
    branches: [ "main", "feature/*" ]
  workflow_dispatch:

jobs:
  # --- ЭТАП 1: ПРОВЕРКА КОДА ---
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install flake8
        run: pip install flake8
      - name: Run lint
        run: flake8 ./backend --count --select=E9,F63,F7,F82 --show-source --statistics

  # --- ЭТАП 2: СБОРКА И ПУШ ОБРАЗОВ ---
  build-and-push:
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/tutorialbox-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/tutorialbox-backend:${{ github.sha }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/tutorialbox-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/tutorialbox-frontend:${{ github.sha }}

  # --- ЭТАП 3: ДЕПЛОЙ В KUBERNETES ---
deploy:
    runs-on: self-hosted  # Твой Arch подхватит эту задачу
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Нам больше не нужно настраивать Kubeconfig через секреты!
      # Твой раннер на Arch уже "видит" minikube.
      
      - name: Update Kubernetes Deployment
        run: |
          # Используем локальный kubectl, который уже настроен на minikube
          kubectl set image deployment/backend-deployment backend=${{ secrets.DOCKER_USERNAME }}/tutorialbox-backend:${{ github.sha }} -n tutorialbox
          kubectl set image deployment/frontend-deployment frontend=${{ secrets.DOCKER_USERNAME }}/tutorialbox-frontend:${{ github.sha }} -n tutorialbox
          
          kubectl rollout status deployment/backend-deployment -n tutorialbox
          kubectl rollout status deployment/frontend-deployment -n tutorialbox
